In [14]:
import torch
from torchvision.datasets import ImageFolder
from torchvision import transforms
import torchvision.utils as vutils
from data import MyLiteDataLoader

import numpy as np

In [4]:
%matplotlib ipympl

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import ipympl

In [16]:
dataroot = '/scratch0/ilya/locDoc/data/celeba_7class'
image_size = 64
batch_size = 128
dataset = ImageFolder(root=dataroot,
                           transform=transforms.Compose([
                            transforms.Resize((image_size,image_size)),
                             #  transforms.CenterCrop(image_size),
                               transforms.ToTensor(),
                               transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
                           ]))
dataloader = torch.utils.data.DataLoader(dataset, batch_size=batch_size,
                                         shuffle=True, num_workers=2)
train_loader = MyLiteDataLoader(dataset, batch_size)

In [17]:
x, y = train_loader.next()

In [18]:
grid = vutils.make_grid(x, nrow=10, padding=2, normalize=True)
plt.figure()
plt.imshow(np.moveaxis(grid.data.cpu().numpy(),0,-1))

FigureCanvasNbAgg()

In [19]:
y

tensor([6, 6, 1, 5, 1, 6, 0, 0, 0, 3, 2, 0, 4, 2, 6, 2, 1, 4, 5, 5, 1, 6, 0, 3,
        6, 3, 2, 3, 2, 0, 3, 0, 1, 0, 0, 6, 0, 6, 1, 0, 3, 5, 6, 6, 5, 1, 1, 3,
        1, 1, 3, 1, 0, 1, 1, 1, 6, 0, 0, 4, 0, 6, 3, 1, 6, 0, 2, 5, 6, 6, 0, 1,
        0, 1, 1, 3, 1, 3, 0, 0, 0, 0, 2, 1, 3, 1, 4, 0, 1, 0, 2, 3, 2, 0, 3, 3,
        3, 3, 0, 0, 0, 0, 6, 2, 3, 5, 1, 0, 4, 3, 0, 3, 4, 0, 2, 2, 2, 6, 0, 0,
        2, 4, 0, 3, 1, 0, 0, 0])

### output as int for wgan

In [49]:
dataset = ImageFolder(root=dataroot,
                           transform=transforms.Compose([
                           transforms.Resize((image_size,image_size)),
                           transforms.Lambda(lambda img: np.moveaxis(np.array(img),-1,0).flatten() ),
                           ]))

In [50]:
dataloader = torch.utils.data.DataLoader(dataset, batch_size=batch_size,
                                         shuffle=True, num_workers=2)
train_loader = MyLiteDataLoader(dataset, batch_size)

In [51]:
x, y = train_loader.next()

AttributeError: Traceback (most recent call last):
  File "/scratch0/ilya/locDoc/miniconda2/envs/venvcuda10/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/scratch0/ilya/locDoc/miniconda2/envs/venvcuda10/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/scratch0/ilya/locDoc/miniconda2/envs/venvcuda10/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 134, in __getitem__
    sample = self.transform(sample)
  File "/scratch0/ilya/locDoc/miniconda2/envs/venvcuda10/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/scratch0/ilya/locDoc/miniconda2/envs/venvcuda10/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 310, in __call__
    return self.lambd(img)
  File "<ipython-input-49-c6eea056f7d9>", line 7, in <lambda>
    transforms.Lambda(lambda img: np.moveaxis(np.array(img),-1,0).flatten().numpy() ),
AttributeError: 'numpy.ndarray' object has no attribute 'numpy'


In [48]:
x[0]

tensor([170, 175, 169,  ...,  45,  30,  19], dtype=torch.uint8)

In [196]:
%matplotlib ipympl

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import ipympl

In [329]:
plt.close('all')

In [131]:
import numpy as np
import matplotlib.pyplot as plt

from skimage.io import imread
#from skimage.data import shepp_logan_phantom
from skimage.transform import radon, rescale

import scipy

In [2]:
from PIL import Image, ImageDraw

In [153]:
im = Image.new('L', (300, 300))
draw = ImageDraw.Draw(im)
draw.ellipse((100, 100, 125, 125), fill=(0), outline=(255))

In [155]:
im_np = np.array(im, dtype=np.float) / 255.0

In [347]:
noise = np.random.normal(0.5,0.50,im_np.shape) 

In [350]:
image = im_np + noise
image /= image.max()

In [351]:
plt.figure()
plt.imshow(image, cmap='gray')

FigureCanvasNbAgg()

In [352]:
theta = np.linspace(0., 180., max(image.shape), endpoint=False)
sinogram = radon(image, theta=theta, circle=True)

/scratch0/ilya/locDoc/miniconda2/envs/venvpyt/lib/python3.7/site-packages/skimage/transform/radon_transform.py:69: UserWarning: Radon transform: image must be zero outside the reconstruction circle
  warn('Radon transform: image must be zero outside the '


In [353]:
plt.figure()
plt.imshow(sinogram, cmap='gray')

FigureCanvasNbAgg()

In [333]:
yax = np.argmax(sinogram,axis=0)
yax_d = np.diff(np.argmax(sinogram,axis=0))

In [334]:
plt.figure()
plt.imshow(sinogram, cmap='gray')
plt.plot(yax)

FigureCanvasNbAgg()

In [335]:
plt.figure()
plt.hist(yax_d)


FigureCanvasNbAgg()

(array([  5.,   8.,  16.,  25., 109.,  85.,  27.,  12.,   6.,   6.]),
 array([-95. , -75.9, -56.8, -37.7, -18.6,   0.5,  19.6,  38.7,  57.8,
         76.9,  96. ]),
 <a list of 10 Patch objects>)

In [336]:
sinogram2 = sinogram.copy()
sinogram2[yax,np.arange(300)] = 0
yax2 = np.argmax(sinogram,axis=0)

In [294]:
from collections import Counter

In [337]:
yax_d_n0 = yax_d[yax_d > 1]
radius_est = np.median(yax_d_n0)

In [342]:
radius_est

20.0

In [338]:
plt.figure()
plt.plot(yax2)
plt.plot(yax)

FigureCanvasNbAgg()

In [346]:
plt.figure()
plt.plot(sinogram[:,0])

FigureCanvasNbAgg()

In [344]:
t = np.arange(300)[yax_good_idx]
both = np.stack([yax,yax2]).mean(axis=0)
x = both[yax_good_idx]

In [345]:
plt.figure()
plt.plot(t,x,'x')

FigureCanvasNbAgg()